### ISSUE TITLE
ENH: Convert post-processing to Transform classes that can be specified in config 

### ISSUE THREAD

**Issue by NickleDave** [vocalpy/vak#537]
e.g. MajorityVote

```toml
[vak.model.TweetyNet]

[vak.model.TweetyNet.output-transform.MajorityVote]
[vak.model.TweetyNet.output_transform]
MinSegmentDur = {min_dur = 2}
```

:thinking: not sure if this is valid TOML, but ... something like this
